platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.4.2

inputs:
- name: lolstats-staging

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    ruby --version

run:
  path: ./lolstats-staging/ci/build.sh
