resources:
- name: lolstats
  type: git
  source:
    uri: https://github.com/kayemk/lolstats.git
    branch: develop
    #private_key: |
    #  -----BEGIN RSA PRIVATE KEY-----
    #  -----END RSA PRIVATE KEY-----

jobs:
- name: Install Dependencies
  serial: true
  plan:
  - get: lolstats
    resource: lolstats
#    trigger: true
- name: Run Tests
  plan:
  - get: lolstats
    passed: [Install Dependencies]
  - task: test
    file: lolstats/ci/build.yml
    #config:

    #  platform: linux
    #  image_resource:
    #    type: docker-image
    #    source: {repository: ubuntu}
    #  run:
    #    path: echo
    #    args: ["Hey! Listen!"]
