resources:
- name: lolstats-staging
  type: git
  source:
    uri: https://github.com/kayemk/lolstats.git
    branch: develop
    #private_key: |
    #  -----BEGIN RSA PRIVATE KEY-----
    #  -----END RSA PRIVATE KEY-----
- name: lolstats-production
  type: git
  source:
    uri: git@github.com:kayemk/lolstats.git
    branch: master
    private_key: ((github_PRIVATE_KEY))

jobs:
- name: Get-Repository
  serial: true
  plan:
  - get: lolstats-staging
    resource: lolstats-staging
    trigger: true
- name: Check
  plan:
  - get: lolstats-staging
    passed: [Get-Repository]
    trigger: true
  - task: check
    file: lolstats-staging/ci/check.yml
- name: Build
  plan:
  - get: lolstats-staging
    passed: [Get-Repository]
    trigger: true
  - task: build
    file: lolstats-staging/ci/build.yml
    params:
      APIKEY: ((api))
- name: Test
  plan:
  - get: lolstats-staging
    passed: [Build]
    trigger: true
  - task: test
    file: lolstats-staging/ci/test.yml
    params:
      APIKEY: ((api))
- name: deploy
  plan:
  - get: lolstats-staging
    passed: [Test]
    trigger: true
  - task: git
    file: lolstats-staging/ci/deploy.yml
  - put: lolstats-production
    params: {repository: lolstats-staging}
#    config:
#      source: {repository: ubuntu}
#
#      run:
#        path: ./lolstats-staging/ci/build.sh
#    #    args: ["Hey! Listen!"]
