resources:
- name: lolstats
  type: git
  source:
    uri: https://github.com/kayemk/lolstats.git
    branch: develop
    #private_key: |
    #  -----BEGIN RSA PRIVATE KEY-----
    #  -----END RSA PRIVATE KEY-----

jobs:
- name: Get-Repository
  serial: true
  plan:
  - get: lolstats
    resource: lolstats
    trigger: true
- name: Build
  plan:
  - get: lolstats
    passed: [Get-Repository]
    trigger: true
  - task: build
    file: lolstats/ci/build.yml
    params:
      LOLAPIKEY: ((api))
- name: Test
  plan:
  - get: lolstats
    passed: [Build]
    trigger: true
  - task: test
    file: lolstats/ci/test.yml
    params:
      LOLAPIKEY: ((api))
#config:

    #  platform: linux
    #  image_resource:
    #    type: docker-image
    #    source: {repository: ubuntu}
    #  run:
    #    path: echo
    #    args: ["Hey! Listen!"]
